//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitorian.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Monitorian.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command-line arguments.
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change contrast.
        /// </summary>
        public static string ChangeContrast {
            get {
                return ResourceManager.GetString("ChangeContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change adjustable range.
        /// </summary>
        public static string ChangeRange {
            get {
                return ResourceManager.GetString("ChangeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy operation log.
        /// </summary>
        public static string CopyOperation {
            get {
                return ResourceManager.GetString("CopyOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save operation log to Desktop?.
        /// </summary>
        public static string CopyOperationMessage {
            get {
                return ResourceManager.GetString("CopyOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defer change until stopped.
        /// </summary>
        public static string DeferChange {
            get {
                return ResourceManager.GetString("DeferChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable changing contrast.
        /// </summary>
        public static string EnableContrast {
            get {
                return ResourceManager.GetString("EnableContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable changing adjustable range.
        /// </summary>
        public static string EnableRange {
            get {
                return ResourceManager.GetString("EnableRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable moving in unison.
        /// </summary>
        public static string EnableUnison {
            get {
                return ResourceManager.GetString("EnableUnison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make operation log.
        /// </summary>
        public static string MakeOperation {
            get {
                return ResourceManager.GetString("MakeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move in unison.
        /// </summary>
        public static string MoveUnison {
            get {
                return ResourceManager.GetString("MoveUnison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by monitors arrangement.
        /// </summary>
        public static string OrderArrangement {
            get {
                return ResourceManager.GetString("OrderArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probe into monitors.
        /// </summary>
        public static string Probe {
            get {
                return ResourceManager.GetString("Probe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred. Save exception log to Desktop?.
        /// </summary>
        public static string RecordExceptionMessage {
            get {
                return ResourceManager.GetString("RecordExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save probe log to Desktop?.
        /// </summary>
        public static string RecordProbeMessage {
            get {
                return ResourceManager.GetString("RecordProbeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan monitors.
        /// </summary>
        public static string Rescan {
            get {
                return ResourceManager.GetString("Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show adjusted brightness.
        /// </summary>
        public static string ShowAdjusted {
            get {
                return ResourceManager.GetString("ShowAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show current number.
        /// </summary>
        public static string ShowNumber {
            get {
                return ResourceManager.GetString("ShowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on sign in.
        /// </summary>
        public static string StartSignIn {
            get {
                return ResourceManager.GetString("StartSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor is not controllable..
        /// </summary>
        public static string StatusNotControllable {
            get {
                return ResourceManager.GetString("StatusNotControllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDC/CI has been failing repeatedly..
        /// </summary>
        public static string StatusReasonDdcFailing {
            get {
                return ResourceManager.GetString("StatusReasonDdcFailing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDC/CI is not supported or enabled..
        /// </summary>
        public static string StatusReasonDdcNotEnabled {
            get {
                return ResourceManager.GetString("StatusReasonDdcNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use large sliders.
        /// </summary>
        public static string UseLargeElements {
            get {
                return ResourceManager.GetString("UseLargeElements", resourceCulture);
            }
        }
    }
}
